[package]
name = 'cord-braid-node-inspect'
description = "CORD Braid node block inspection tool."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
clap = { workspace = true, features = ["derive"] }
codec = { workspace = true }
thiserror = { workspace = true }
sc-cli.workspace = true
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-service.workspace = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-io.workspace = true
sp-io.default-features = true
sp-runtime.workspace = true

[features]
runtime-benchmarks = [
	"sc-service/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
