[package]
name = 'cord-braid-node-rpc'
description = "CORD Braid node RPC methods."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
jsonrpsee = { features = ["server"], workspace = true }
cord-primitives.workspace = true
cord-primitives.default-features = true

pallet-transaction-payment-rpc.workspace = true
pallet-transaction-payment-rpc.default-features = true
sc-chain-spec.workspace = true
sc-chain-spec.default-features = true
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-consensus-babe.workspace = true
sc-consensus-babe.default-features = true
sc-consensus-babe-rpc.workspace = true
sc-consensus-babe-rpc.default-features = true
sc-consensus-grandpa.workspace = true
sc-consensus-grandpa.default-features = true
sc-consensus-grandpa-rpc.workspace = true
sc-consensus-grandpa-rpc.default-features = true
sc-rpc.workspace = true
sc-rpc.default-features = true
sc-sync-state-rpc.workspace = true
sc-sync-state-rpc.default-features = true
sc-transaction-pool-api.workspace = true
sc-transaction-pool-api.default-features = true

sp-api.workspace = true
sp-api.default-features = true
sp-block-builder.workspace = true
sp-block-builder.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-consensus.workspace = true
sp-consensus.default-features = true
sp-consensus-babe.workspace = true
sp-consensus-babe.default-features = true
sp-keystore.workspace = true
sp-keystore.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-application-crypto.workspace = true
sp-application-crypto.default-features = true
sp-statement-store.workspace = true
sp-statement-store.default-features = true

substrate-frame-rpc-system.workspace = true
substrate-frame-rpc-system.default-features = true
substrate-state-trie-migration-rpc.workspace = true
substrate-state-trie-migration-rpc.default-features = true
